services:
  - type: web
    name: flet-app
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: FLET_SECRET_KEY
        generateValue: true